version = 0.1

[default.global.parameters]
stack_name = "publish-data-s3-sar"
s3_bucket = "mytiki-sam-deploy"
s3_prefix = "publish/data/s3/sar"
region = "us-east-2"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_AUTO_EXPAND"
]
image_repositories = []
parameter_overrides = []
